# Generated by Django 3.0.3 on 2020-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
