# Generated by Django 2.2.5 on 2020-03-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_total_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filter_todos_by',
            field=models.CharField(default='all_todos', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_of_important_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
