# Generated by Django 2.2.5 on 2020-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200331_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='todos_completed_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='todos_created_this_week',
            field=models.IntegerField(default=0),
        ),
    ]
