# Generated by Django 2.2.5 on 2020-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200331_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='todos_completed_on_time',
            field=models.IntegerField(default=0),
        ),
    ]
