# Generated by Django 2.2.5 on 2020-04-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_todos_completed_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='efficiency_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='generated_insights_this_week',
            field=models.BooleanField(default=False),
        ),
    ]
