# Generated by Django 2.2.5 on 2020-04-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200403_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='efficiency_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='efficiency_change_type',
            field=models.CharField(default='NOT_PROVIDED', max_length=100),
        ),
    ]
