# Generated by Django 2.2.5 on 2020-04-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200403_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_insights_date',
        ),
    ]
