# Generated by Django 3.0.3 on 2020-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_last_insights_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='todos_completed_created_long_ago',
            field=models.IntegerField(default=0),
        ),
    ]
