# Generated by Django 3.0.3 on 2020-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_default_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='num_of_important_tasks',
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
