# Generated by Django 3.0.3 on 2020-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_profile_has_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='filter_todos_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sort_todos_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='todos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_todos',
        ),
    ]
