# Generated by Django 3.0.3 on 2020-05-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200510_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='important_tasks_completed_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='missed_tasks_this_week',
            field=models.IntegerField(default=0),
        ),
    ]
