# Generated by Django 3.0.3 on 2020-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200510_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='todos_completed_after_due_date',
            field=models.IntegerField(default=0),
        ),
    ]
