# Generated by Django 3.0.3 on 2020-05-17 15:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_todos_completed_after_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.get_user_dp_dir),
        ),
    ]
