# Generated by Django 3.0.3 on 2020-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200517_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ver_2_informed',
            field=models.BooleanField(default=False),
        ),
    ]
