# Generated by Django 3.0.3 on 2020-05-24 10:58

from django.db import migrations, models
import timezone_field.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_ver_2_informed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_img.jpg', upload_to=users.models.get_user_dp_dir),
        ),
    ]
