# Generated by Django 2.2.5 on 2020-02-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_todo_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='content',
        ),
    ]
