# Generated by Django 2.2.5 on 2020-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0005_remove_todo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todos',
            field=models.IntegerField(default=0),
        ),
    ]
