# Generated by Django 2.2.5 on 2020-02-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_todo_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todos',
        ),
    ]
