# Generated by Django 2.2.5 on 2020-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0008_auto_20200305_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='past_due_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
