# Generated by Django 3.0.3 on 2020-03-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0009_auto_20200305_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
