# Generated by Django 2.2.5 on 2020-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0010_auto_20200317_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('parent_task', models.CharField(max_length=150)),
                ('identification_id', models.IntegerField(default='NOT_PROVIDED')),
            ],
        ),
    ]
