# Generated by Django 2.2.5 on 2020-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0012_todo_num_of_subtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text="Add anything that's important to the task")),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('parent_task', models.CharField(max_length=150)),
                ('identification_id', models.IntegerField(default='NOT_PROVIDED')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.BooleanField(default=False),
        ),
    ]
