# Generated by Django 3.0.3 on 2020-05-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0017_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='parent_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo.TaskList'),
        ),
    ]
