# Generated by Django 3.0.3 on 2020-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0019_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
