# Generated by Django 3.0.3 on 2020-05-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0020_todo_has_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
