# Generated by Django 3.0.3 on 2020-05-25 08:44

import ToDo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0021_auto_20200525_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='content',
            field=models.FileField(default=None, help_text='Add important documents or pictures', upload_to=ToDo.models.get_attachment_dir),
            preserve_default=False,
        ),
    ]
